defaultEntryPoints = ["http","https"]
debug = false
logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "carlosedp@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
caServer = "https://acme-v01.api.letsencrypt.org/directory"
[acme.httpChallenge]
entryPoint="http"


# Web configuration backend
[web]
  address = ":8080"

[web.metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]
  entryPoint = "traefik"

# Docker configuration backend
[docker]
  domain = "cloud.carlosedp.com"
  watch = true
  exposedbydefault = false
